[package]
name = "opcua-streams-types"
version = "0.1.0"
authors = ["jungh <hauke.jung@outlook.de>"]
edition = "2018"

[dependencies]
serde = {version="1.0.110", features = ["derive"] }
serde_derive = "1.0.110"
serde_json = "1.0.53"